import { Command } from 'commander';
import chalk from 'chalk';

function getCommandNames(cmd: Command): string[] {
  const names: string[] = [];
  for (const c of cmd.commands) {
    if (!c.name().startsWith('_')) {
      names.push(c.name().split(' ')[0]); // "create <x>" -> "create"
    }
  }
  return names;
}

function buildZshScript(program: Command): string {
  const lines: string[] = [
    '#compdef whales',
    '# Generated by whales completion --shell zsh',
    '',
    '_whales_commands() {',
    '  local -a cmds',
    `  cmds=(${program.commands.map((c) => `'${c.name()}:${(c as any).description?.() || c.name()}'`).join(' ')})`,
    '  _describe "command" cmds',
    '}',
    '',
    '_whales_subcommands() {',
    '  local -a subcmds',
    '  case $words[2] in',
  ];

  for (const cmd of program.commands) {
    const sub = getCommandNames(cmd);
    if (sub.length > 0) {
      lines.push(`    ${cmd.name()})`);
      lines.push(`      subcmds=(${sub.map((s) => `'${s}'`).join(' ')})`);
      lines.push('      _describe "subcommand" subcmds');
      lines.push('      ;;');
    }
  }

  lines.push('    *)');
  lines.push('      ;;');
  lines.push('  esac');
  lines.push('}');
  lines.push('');
  lines.push('_whales() {');
  lines.push('  local context state state_descr line');
  lines.push('  typeset -A opt_args');
  lines.push('');
  lines.push('  _arguments -C \\');
  lines.push("    '1: :_whales_commands' \\");
  lines.push("    '2: :_whales_subcommands'");
  lines.push('}');
  lines.push('');
  lines.push('compdef _whales whales');
  lines.push('');
  return lines.join('\n');
}

function buildBashScript(program: Command): string {
  const topLevel = program.commands.map((c) => c.name().split(' ')[0]).join(' ');
  const lines: string[] = [
    '# Generated by whales completion --shell bash',
    '',
    '_whales_completions() {',
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    '  local prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '',
    '  if [ $COMP_CWORD -eq 1 ]; then',
    `    COMPREPLY=($(compgen -W "${topLevel}" -- "$cur"))`,
    '  elif [ $COMP_CWORD -eq 2 ]; then',
    '    case "$prev" in',
  ];

  for (const cmd of program.commands) {
    const sub = getCommandNames(cmd);
    if (sub.length > 0) {
      lines.push(`      ${cmd.name()})`);
      lines.push(`        COMPREPLY=($(compgen -W "${sub.join(' ')}" -- "$cur"))`);
      lines.push('        ;;');
    }
  }

  lines.push('      *)');
  lines.push('        COMPREPLY=()');
  lines.push('        ;;');
  lines.push('    esac');
  lines.push('  fi');
  lines.push('}');
  lines.push('');
  lines.push('complete -F _whales_completions whales');
  lines.push('');
  return lines.join('\n');
}

export function createCompletionCommand(): Command {
  return new Command('completion')
    .description('Generate shell completion script for tab autocomplete')
    .option('-s, --shell <shell>', 'Shell type (zsh|bash)', 'zsh')
    .action(async (options, command) => {
      const prog = command.parent as Command;
      const shell = (options.shell || 'zsh').toLowerCase();

      if (shell === 'zsh') {
        console.log(buildZshScript(prog));
      } else if (shell === 'bash') {
        console.log(buildBashScript(prog));
      } else {
        console.error(chalk.red(`Unsupported shell: ${shell}. Use zsh or bash.`));
        process.exit(1);
      }
    });
}
